server:
  port: 8085

spring:
  application:
    name: "viewreceiptmicroservice"
  config:
    import: "optional:configserver:http://localhost:8761/"

  management:
    endpoints:
      web:
        exposure:
          include: "*"

info:
  app:
    name: "viewreceiptmicroservice"
    description: "receipt generation Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      org:
        receipt: DEBUG

resilience4j.ratelimiter:
  instances:
    squareLimit:
      limitForPeriod: 1000
      limitRefreshPeriod: 60s
      timeoutDuration: 0
