server:
  port: 8081

spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8761/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server Application"
    version: "1.0.0"