server:
  port: 8082

spring:
  application:
    name: "studentmicroservice"
  datasource:
    url: jdbc:h2:mem:student_information
    driver-class-name: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
  config:
    import: "optional:configserver:http://localhost:8761/"

  management:
    endpoints:
      web:
        exposure:
          include: "*"

info:
  app:
    name: "studentmicroservice"
    description: "Student Management Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      org:
        studentmanagement: DEBUG


kafka:
  bootstrap-servers: localhost:29092  # Adjust if using a different Kafka host
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer